### ISSUE TITLE
Fix the introspection GitHub action tests (Feb 2024)

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1542] opened 2024-02-04 18:23 UTC
**Is your feature request related to a problem? Please describe.**

1. Our introspection PR tests have been failing. This seems to be caused by code that references now deprecated Event and User task functionality.
2. Here is a recent example:
    1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7774376104/job/21199116216?pr=1539

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/5d9ec319-72ed-4656-a2f3-e9db265373e0)

**Describe the solution you'd like**

This issue has two parts. We have a history of this error repeating itself and it needs to be finally resolved permanently

_Short Term Solution_
1. Update  the offending code to make the introspection tests pass
2. All existing tests must pass and must be valid tests of the code base
3. No other functionality must be affected

_Long Term Solution_
1. Determine what is causing the problem where the API and Admin repos are periodically out of sync and fix it.
1. We think it may be caused by this issue not being successfully resolved. You may need to coordinate with the person assigned this issue
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1599
1. **NOTE:** This may mean creating a GitHub action to automatically create issues when an API PR is merged where the schema is updated.
3. All existing tests must pass and must be valid tests of the code base
4. No other functionality must be affected

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

- @Cioppolo14 This will be good to track

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment] 2024-02-04 18:38
I would like to work on this issue.

**Comment by palisadoes** [comment] 2024-02-04 18:44
Please read the updated long term solution section

**Comment by akhilender-bongirwar** [comment] 2024-02-05 15:25
@palisadoes Sir, 

For the **Short-Term Solution** to the introspection PR test failure, we can revert this #1499 in `talawa-admin` for now. We should wait for this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1762) in `talawa-api` to be merged first. Afterward, we can merge that PR into `talawa-admin`.

**Comment by akhilender-bongirwar** [comment] 2024-02-06 20:36
@palisadoes  Sir, just a quick follow-up on the short-term solution proposal for the introspection PR test failure. I am  still awaiting your opinion. Thank you.

**Comment by palisadoes** [comment] 2024-02-06 20:45
We didn't realize that the two PRs were linked.

I'd prefer not to revert. Will the introspection be fixed after the API merge?

**Comment by palisadoes** [comment] 2024-02-06 20:46
What about the line term solution?

**Comment by akhilender-bongirwar** [comment] 2024-02-07 10:30
> We didn't realize that the two PRs were linked.
> 
> I'd prefer not to revert. Will the introspection be fixed after the API merge?

Yes, sir the introspection will be fixed after the API merge.

**Comment by akhilender-bongirwar** [comment] 2024-02-07 11:50
> What about the line term solution?

Sir, these are few points I would like to address

**Observations**
1. The `talawa-api schema` is ahead of the `admin schema`, which has not caused any issues in the regular functioning of the `talawa-admin` portal.

2. Attributes required for new features in the admin `schema` have been sourced from `talawa-api`.

3. The `GraphQL introspection` failure typically occurs when new attributes are declared in the admin schema but are not defined in the API schema. These attributes often lack defined logic, resulting in potential failures for associated actions/functions.  

4. We already have a dedicated `Graphql-Inspector` GitHub Action to handle the scenario mentioned above.

**Fix**
- When adding a new attribute in `admin schema` for a fix or feature, it's crucial to declare that attribute in the `API schema` first and then use it in the admin. This approach prevents introspection errors and ensures the smooth operation of our application without errors.

**Remarks**

- Sir, IMO, it is better we have the `API schema` ahead of the `admin schema`. This ensures that development is not halted in the API, and it allows us to create new features in admin using those attributes.
-  This practice does not pose any issues for the development server.
-  We should only be cautious about preventing errors when new attributes added to the admin schema are not declared in the API schema. Until this error is addressed, everything else will function correctly.

**Comment by akhilender-bongirwar** [comment] 2024-02-07 17:46
> > What about the line term solution?
> 
> Sir, these are few points I would like to address
> 
> **Observations**
> 
>     1. The `talawa-api schema` is ahead of the `admin schema`, which has not caused any issues in the regular functioning of the `talawa-admin` portal.
> 
>     2. Attributes required for new features in the admin `schema` have been sourced from `talawa-api`.
> 
>     3. The `GraphQL introspection` failure typically occurs when new attributes are declared in the admin schema but are not defined in the API schema. These attributes often lack defined logic, resulting in potential failures for associated actions/functions.
> 
>     4. We already have a dedicated `Graphql-Inspector` GitHub Action to handle the scenario mentioned above.
> 
> 
> **Fix**
> 
>     * When adding a new attribute in `admin schema` for a fix or feature, it's crucial to declare that attribute in the `API schema` first and then use it in the admin. This approach prevents introspection errors and ensures the smooth operation of our application without errors.
> 
> 
> **Remarks**
> 
>     * Sir, IMO, it is better we have the `API schema` ahead of the `admin schema`. This ensures that development is not halted in the API, and it allows us to create new features in admin using those attributes.
> 
>     * This practice does not pose any issues for the development server.
> 
>     * We should only be cautious about preventing errors when new attributes added to the admin schema are not declared in the API schema. Until this error is addressed, everything else will function correctly.

@palisadoes, sir, I would like to know your thoughts on this.

**Comment by palisadoes** [comment] 2024-02-08 03:51
>We should only be cautious about preventing errors when new attributes added to the admin 
> schema are not declared in the API schema. Until this error is addressed, everything else will 
> function correctly.

How could we adjust our introspection test to fail in this case but not when the API is ahead of Admin?

**Comment by akhilender-bongirwar** [comment] 2024-02-08 17:54
@palisadoes sir, 
- The current `Graphql-Inspector` Github action is already performing the same task. This is evident from the fact that the action was successful until the #1483  was merged [actions](https://github.com/PalisadoesFoundation/talawa-admin/pull/1483/checks).  However, it started failing right after the merge of this [PR](https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7684154428/job/20940664469?pr=1499). 
- This workflow correctly identified the cause, stating:
```
[log] - Field 'id' is not defined by type 'UpdateUserInput'.
 - Field 'applangcode' is not defined by type 'UpdateUserInput.'
 ```
 - These were the exact fields added to the schema which were not defined in the schema in the api.

**Comment by palisadoes** [comment] 2024-02-08 20:54
OK, thanks

**Comment by palisadoes** [comment] 2024-02-08 20:57
1. Based on this discussion, it sounds like we really have an issue.
2. I'll close the issue

**Closed** 2024-02-08 20:57 UTC
Labels: bug, feature request
