### ISSUE TITLE
Include the name of the organization on all pages for the admin.

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-admin#503] opened 2023-02-24 18:05 UTC
**Is your feature request related to a problem? Please describe.**
To prevent admins from losing track of where they are and the group they are making changes for.

- Refer to this video for context: https://youtu.be/ix3eSReJj2k

**Describe the solution you'd like**
For admins to keep track of where they are and the group they are making changes for, the organization name should show on every page.

**Approach to be followed**
- We want to minimize changes to the existing design. Keep the current design.
- Code coverage for all files editor must be 100%

**Comment by noman2002** [comment] 2023-02-24 18:59
@rishav-jha-mech You already have 3 issues assigned to you. As per rules maximum of 2 issues can be assigned at once. Please get the PRs merged before asking for more.

**Comment by aviraldevv** [comment] 2023-02-24 22:26
@anwersayeed @noman2002 I would like to work on this issue but I can start working on it latest from next week as I am having my exams. If its not an issue I can be assigned.

**Comment by anurag0006** [comment] 2023-02-25 05:06
I would like to work on this issue

**Comment by anurag0006** [comment] 2023-02-25 05:10
[Screencast from 24-02-23 07:50:12 PM IST.webm](https://user-images.githubusercontent.com/107215525/221339525-06467d9c-4237-46a6-86a7-25b41fb5205d.webm)
This is something that i implemented in seeting's page...Is this that you want us to implement for the whole portal or any approach for this issue?

**Comment by palisadoes** [comment] 2023-02-25 05:49
@aviraldevv If the issue is still open when you are available, then we will assign it to you

**Comment by anurag0006** [comment] 2023-02-25 05:52
@palisadoes  I would like to work on this issue...Am totally free and dont have any pending issues or PRs

**Comment by palisadoes** [comment] 2023-02-25 05:53
> [Screencast from 24-02-23 07:50:12 PM IST.webm](https://user-images.githubusercontent.com/107215525/221339525-06467d9c-4237-46a6-86a7-25b41fb5205d.webm)( a dynamic subheading which changes as the user clicks on different buttons to tell him which button has he clicked and what setting is he/she trying to changes)
> 
> This is something that i implemented in seeting's page...Is this that you want us to implement for the whole portal or any approach for this issue?
> 

- Please refer to this video for context it is explained there:  https://youtu.be/ix3eSReJj2k

**Comment by aviraldevv** [comment] 2023-02-25 06:02
@palisadoes my exams are until 3rd March after that I am free to work full time. I will submit PR for this as early as possible.

**Comment by palisadoes** [comment] 2023-02-27 20:53
The wording of the issue is not clear. We meant organization, not group. It's not the breadcrumb task that is of concern at this time.

1. The issue is that after you select an organization there is no way to clearly see which organization you are editing.
1. This could cause super admins to do actions on the wrong organization.

**Comment by palisadoes** [comment] 2023-02-28 09:30
Is this information visible on every single management page for the organization? If not, think of the easiest way for this to happen.

**Comment by anurag0006** [comment] 2023-02-28 23:39
Most of the functionality on the management page is not working right now but i made some changes as follows:(here the name of the organization is "testOrganization")
![WhatsApp Image 2023-03-01 at 5 00 34 AM](https://user-images.githubusercontent.com/107215525/222006857-f680d56f-bec6-474c-8ceb-f0ffbc7b83c0.jpeg)
![WhatsApp Image 2023-03-01 at 5 00 14 AM](https://user-images.githubusercontent.com/107215525/222006860-e8be13a8-e038-4d24-8942-de6759e9286e.jpeg)



Here is how it initially looked(screenshot):
![image](https://user-images.githubusercontent.com/107215525/222007526-54d20b2a-09f0-40b4-b130-477b28c043c0.png)






Along with this, i also thought of adding a toast message to the user as soon as he deletes a organization, it will display for 1 sec and then the page will be rerouted back to the orglist page..(screencast as follows)
[Screencast from 01-03-23 05:06:57 AM IST.webm](https://user-images.githubusercontent.com/107215525/222007731-b6959bf3-a436-4e19-b2d1-3bc14882ff13.webm)

**Comment by anurag0006** [comment] 2023-02-28 23:40
@palisadoes , Is there anything i need to change in this or should i make the PR for it?

**Comment by palisadoes** [comment] 2023-03-01 00:45
- Still too difficult.
- What about changing the to menu bar with either text or an image? 

https://support.google.com/a/answer/96474?hl=en

**Comment by anurag0006** [comment] 2023-03-01 10:42
@palisadoes, I tried to work on this as you said, but here we get 2 problem:
1. the image functionality is not working yet so we have to fix a static image for all the organizations for a while until the image functionality is fixed..
2. Everyone will upload images with different dimensions for their organization,but  we need a proper 45x45 pixels image to fit that section, if the image is smaller or larger, it will not look good as the image might get blurred or overstretched....

So i thought to add the name of Organization instead: i added it to the navbar and it will be displayed over all the pages connected to the organization i.e. people , events , posts, plugins , etc :(as shown in picture)
![WhatsApp Image 2023-03-01 at 4 09 08 PM](https://user-images.githubusercontent.com/107215525/222116305-e1ae3134-ddd7-42bc-b1bf-9f0f14634b6e.jpeg)

Maybe a bit of styling will make it look good...

should i go ahead with this?

**Comment by palisadoes** [comment] 2023-03-01 11:03
Thanks for the update

1. Can you replace the Talawa logo with the alt text of the organizations logo image, which in this case would be the name of the organization? When image upload works this could be replaced by the image?
1. The Talawa logo would only remain for the super admin specific screens

**Comment by anurag0006** [comment] 2023-03-01 15:06
@palisadoes, I think this is what was required...Please have a look and give me the review:
[Screencast from 01-03-23 08:20:09 PM IST.webm](https://user-images.githubusercontent.com/107215525/222176660-e02ca681-cc00-4e3f-ab18-5dd69847d5ba.webm)

**Comment by palisadoes** [comment] 2023-03-01 21:47
The reason for this is to save space in the menu bar for possible new links in future.

Thanks for the effort. The result is spirit to what we had before.

**Comment by palisadoes** [comment] 2023-03-01 21:50
Please submit a PR with the appropriate tests. We don't want this feature to break in future

**Closed** 2023-03-03 15:05 UTC
Labels: feature request, gsoc
