### ISSUE TITLE
Post search only works once 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1261] opened 2023-12-22 20:44 UTC
**Describe the bug**
- Searching posts only works once after creating posts

**To Reproduce**

1. Create new database
2. Login as superadmin
3. Select the Angel Foundation organization
4. Add posts. Try uploading invalid image types.
5. Searching doesn't work consistently

**Expected behavior**
- Searching posts must work all the time

**Actual behavior**
- See above

**Screenshots**
1. Original posts
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/abf42026-862d-43e7-9d4a-aa5c9c5830b7)
1. Search results exact match
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/56010a16-feab-4602-bbac-8a673bbfc14b)
1. Search results when looking for text that is not present. It's the same as before
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/836eb415-70db-4873-a742-60f3ac4059e4)

**Additional details**
- See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RAGHAV-N5** [comment] 2023-12-23 01:21
can I work on this issue? I have submitted pull request to the previously assigned issue. Please assign me this issue .

**Comment by akhilender-bongirwar** [comment] 2023-12-23 04:45
@Cioppolo14, I would like to work on this issue. Please assign me.

**Comment by AmitSharma512** [comment] 2023-12-23 07:03
@palisadoes I would like to work on this.

**Comment by Min2who** [comment] 2023-12-23 07:40
@Cioppolo14 @palisadoes can i work on this

**Comment by akhilender-bongirwar** [comment] 2023-12-26 13:01
@palisadoes, I'm unable to reproduce the issue as searching posts appears to be functioning correctly. Please review the following videos:

- Demonstrates the expected error message when attempting to upload an invalid image type.

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/6c9b31ff-b093-4061-bfac-42afbbec5898

- Demonstrates successful search functionality when a valid image type is uploaded.

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/3b703499-c140-454e-80eb-4c9d6dc4bf3d

@Cioppolo14, Could you please verify?

**Comment by akhilender-bongirwar** [comment] 2023-12-26 14:08
@palisadoes, I think the issue is #1292 . Please check

**Comment by Cioppolo14** [comment] 2023-12-29 02:33
@akhilender-bongirwar Thank you, this is probably it. I'm going to close this issue for now.

**Closed by Cioppolo14** 2023-12-29 02:33 UTC
Labels: bug, invalid
