### ISSUE TITLE
Bug Report: Improper behavior of the create post and pinning post

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1619] opened 2024-02-25 22:05 UTC
**Describe the bug**
We are not able to create a post with a title without pinning the post. Also when we pin the post and unpin it. It shows the same thing when we again try to pin it. Then after update the post and again adding a title to the post we are not able to pin in again. What should the actual flow of this feature. 
**To Reproduce**

1. Go to the create post page. 
2. Then try to create a post without pinning it with a title. 
3. After pinning the post and unpinning it. You again will not able to pin it.

**Expected behavior**
I am not clear what should be the flow. should the post with a title must be pinned. And after pinning it the title should be removed as showing. Please tell me. I will implement.

**Actual behavior**
Please see the video.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/c482f1a1-97f9-4ea4-b451-7a8854a9a724

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by skbhagat0502** [comment] 2024-02-25 22:12
@palisadoes @aashimawadhwa I saw issue number #1486 , which is related to this. According to the issue we must not able to create a post with title without pinning it. But what about pinning after updating the post. Also how we are able to add the title without pinning it in the update post modal. 

I would like to work on this issue. Please tell me what should be the flow. Should there be a pinning button in the update post,which should appear only if we try to add the title or only if I add the title then we must tell user to pin the post.

**Comment by Cioppolo14** [comment] 2024-03-11 00:41
Unassigning due to no activity or PR.

**Comment by varshith257** [comment] 2024-03-11 03:44
@Cioppolo14 isn't it duplicate of #1595

**Comment by Cioppolo14** [comment] 2024-03-11 12:06
Yes, thank you.  I thought it was a duplicate but couldn't find it.  Thank you for the link.  Closing this as a duplicate.

**Closed by Cioppolo14** 2024-03-11 12:05 UTC
Labels: bug, feature request
