### ISSUE TITLE
Implement login for Admin and Super-Admin 

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-admin#493] opened 2023-02-22 05:43 UTC
**Is your feature request related to a problem? Please describe.**
Admins of several organizations may control the personnel and operations of their own organizations using talawa-admin. Presently, when you attempt to connect into talawa-admin, you are logged in as super-admin and are able to access information for other organizations in addition to your own.
You can refer to the image below.
![11](https://user-images.githubusercontent.com/58592306/220532908-12fc733f-8ed6-4c02-b83a-cf9a8f42f1e8.PNG)

**Describe the solution you'd like**
The login screen should stay the same, but when a user enters their credentials, it should automatically determine if they are an admin or a super-admin. Although the super admin might travel down through all the organizations, the admin should only be allowed access to their specific organization.

**Describe alternatives you've considered**
The contributor can come up with her/ his own ideas.

**Approach to be followed**
- We want to minimize changes to the existing design. Keep the current design.
- Code coverage for all files editor must be 100%

**Additional context**
 - API calls may have to be modified and the relevant issues created

**Comment by Manoramsharma** [comment] 2023-02-22 09:50
Hi @tasneemkoushar , I would like to work on this issue. We just need to render the existing code over a condition of pre determining the user as admin and super-admin just after the login.

**Comment by tasneemkoushar** [comment] 2023-03-03 09:22
@Manoramsharma What's the status?

**Comment by Manoramsharma** [comment] 2023-03-03 15:42
Hi @tasneemkoushar I have done with the asked changes but as I already mentioned in talawa-admin channel I am getting that yarn error, which is producing unnecessary changes by changing yarn.lock file due to which I am unable to make a PR. Here is the link to the issue which I mentioned.
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1677756698705999

**Comment by palisadoes** [comment] 2023-03-04 03:31
Please merge your repo with the upstream, then reinstall the  packages. There have been many changes.

**Comment by palisadoes** [comment] 2023-03-06 00:45
@Manoramsharma Did you get this fixed?

**Comment by Manoramsharma** [comment] 2023-03-06 10:44
<img width="539" alt="image" src="https://user-images.githubusercontent.com/84619980/223087699-be4bd24e-6e3a-4647-9875-3a7aa4f9b0af.png">
Still this error? The problem is many of our packages are deprecated that are present in our `yarn.lock` file so modification in yarn.lock file is requested which I forbidden by using `yarn --immutable` flag in yarn command for installing the dependencies , If I use `yarn` simply to install the dependencies it will modify the yarn.lock file which is not accepted

**Comment by Manoramsharma** [comment] 2023-03-06 10:47
Also @palisadoes Talawa-admin is using yarn v1 which is deprecated and not maintained anymore. So, getting errors with it is trivial. If we try upgrading it to newer version the whole app breaks.

**Comment by palisadoes** [comment] 2023-03-06 13:24
Why is this not affecting others? Are you adding new packages?

**Comment by palisadoes** [comment] 2023-03-06 21:11
1. Please submit a PR for this.
1. Should we create an issue to upgrade packages for Talawa-Admin in the mean time?

**Comment by faraz16iqbal** [comment] 2023-03-07 05:59
@palisadoes is this issue still open?

**Comment by anshgoyalevil** [comment] 2023-03-07 06:03
@faraz16iqbal 

Thanks for contributing to Talawa projects. 

This issue is already assigned to @Manoramsharma 

Please check other issues across different Talawa Repos, and select the ones which are not assigned to anyone

**Comment by xoldyckk** [comment] 2023-03-07 07:16
> Why is this not affecting others? Are you adding new packages?

Yarn v1 has reached end of life. Currently yarn is on v3 and it's not backward compatible, because there's many core changes related to its internal workings. Talawa-admin is deeply integrated with yarn v1 and create-react-app(this too is a cause for major disruptions and warnings) and making use of yarn v3 breaks the app.

**Comment by palisadoes** [comment] 2023-03-07 13:17
@xoldyckk Should we create an issue to upgrade to Yarn v3?

**Comment by palisadoes** [comment] 2023-03-07 14:02
I'll make it npm

**Comment by Manoramsharma** [comment] 2023-03-07 15:00
> > @xoldyckk Should we create an issue to upgrade to Yarn v3?
> 
> Yeah. Technically if it's going to be done, there's no need to upgrade to yarn v3. We can simply start using npm. Then both talawa-api and talawa-admin will be using the same package manager.

It will be easier to manage in case of npm , also when both of our projects will be using the same package manager there will be less breaking changes.

**Closed** 2023-03-10 20:56 UTC
Labels: feature request, gsoc
