### ISSUE TITLE
[userTypeFix]: Organizations not Visible Error

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-admin#1768] opened 2024-03-23 16:06 UTC
**Describe the bug**

1. After login as Admin/SuperAdmin, the organizations aren't rendered/loaded correctly
1. They flash on briefly, then the `not found` error appears

**NOTE**

1. It appears to work OK for the test users here
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#user-accounts-and-organizations
2. It does not work for a newly registered `LAST_RESORT_SUPERADMIN_EMAIL`
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#setting-up-env-last_resort_superadmin_email-parameter-in-the-env-file

**To Reproduce**

1. Login as Admin/SuperAdmin
2. Look at My Organizations Screen

Organizations Screen show Organization not found error

**Expected behavior**

Organizations have to be loaded correctly without any issues

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/4077084f-47d4-4093-8456-0cbd08f3ebb4

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Doraemon012** [comment] 2024-03-23 16:50
@palisadoes I would like to work on this issue, please assign it to me.

**Comment by palisadoes** [comment] 2024-03-23 16:53
1. It appears to work OK for the test users here
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#user-accounts-and-organizations
2. It does not work for a newly registered `LAST_RESORT_SUPERADMIN_EMAIL`
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#setting-up-env-last_resort_superadmin_email-parameter-in-the-env-file

**Comment by palisadoes** [comment] 2024-03-23 17:14
@Doraemon012 Please write a test to make sure the superadmin of last resort doesn't have this issue again.

**Comment by AVtheking** [comment] 2024-03-24 03:45
@Doraemon012 the issue is in this line 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/132201033/fd5e1872-8b41-48ea-b517-71a8c976855a)
add check for superAdmin also so that it shows organization for super admin even if admin For field is empty

**Comment by palisadoes** [comment] 2024-03-24 17:52
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by palisadoes** [comment] 2024-03-30 23:52
@Doraemon012 

This is a really glaring flaw in our app logic. How is your progress on resolving this?

**Comment by Doraemon012** [comment] 2024-04-04 11:25
@palisadoes I have raised a PR for this. Please take a look.

**Closed** 2024-04-04 16:53 UTC
Labels: bug, good first issue, feature request, userTypeFix, GSoC Priority
