### ISSUE TITLE
[BUG REPORT] MEMBERSHIP_REQUEST query is not suitable according to api

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa-admin#822] opened 2023-03-29 02:31 UTC
**Describe the bug**
The membership reqest quesry is not working. On the setting page in the membership request section, no data is shown even though multiple request exist already.

**To Reproduce**

1. Make a membership request on private org from talawa-mobile
2. See the request section

**Expected behavior**
should show all the data
**Actual behavior**
show nothing for now.
**Screenshots**
**Additional details**
talawa-api no-longer follow nested schemesas result the talawa-admin got left behind. Also for more ref see/comment this [discussion](https://github.com/PalisadoesFoundation/talawa/discussions/1726) 
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment] 2023-03-29 02:34
If possible i would like to correct this.

**Comment by BhuvanAde** [comment] 2023-03-29 03:05
If @Ayush0Chaudhary is not Interested. Can you @palisadoes assign me this issue?

**Comment by palisadoes** [comment] 2023-04-09 03:33
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by BhuvanAde** [comment] 2023-04-09 03:46
Can I work on this issue please ? @palisadoes

**Comment by saiteja13427** [comment] 2023-05-06 13:53
@palisadoes Can I work on this issue?

**Comment by palisadoes** [comment] 2023-05-31 02:58
unassigning due to inactivity

**Comment by palisadoes** [comment] 2023-12-02 14:47
> Is this open? If yes, please assign to me

Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by LakshyaSatpal** [comment] 2023-12-02 16:21
@palisadoes Got it, thanks.
I got PR merged linked to [#1043](https://github.com/PalisadoesFoundation/talawa-admin/issues/1043) with 100% code coverage, but the issue still persists assigned to me, Idk why. Can you please check?

**Comment by LakshyaSatpal** [comment] 2023-12-03 21:07
Can this be assigned to me?

**Comment by LakshyaSatpal** [comment] 2023-12-04 23:53
Hey @Ayush0Chaudhary, wanted some more clarity, about the issue. 
- first, I don't see `MEMBERSHIP_REQUEST` query being used on the `/requests` page, or even anywhere in the repo. I think the issue might be with the `USER_LIST_REQUEST` query, which I need to confirm.
- second, just to confirm, the issue is regarding the `src/screens/Requests/Requests.tsx` page, right?

**Comment by LakshyaSatpal** [comment] 2023-12-11 01:13
unassigning myself.

**Comment by Shubh152** [comment] 2023-12-15 09:32
If this issue is open and available, Please assign this to me.

**Comment by Shubh152** [comment] 2023-12-23 14:15
unassigning myself

**Comment by KrishavRajSingh** [comment] 2023-12-25 08:25
I would like to work on this

**Comment by KrishavRajSingh** [comment] 2023-12-25 17:23
> **Describe the bug** The membership reqest quesry is not working. On the setting page in the membership request section, no data is shown even though multiple request exist already.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Make a membership request on private org from talawa-mobile
> 2. See the request section
> 
> **Expected behavior** should show all the data **Actual behavior** show nothing for now. **Screenshots** **Additional details** talawa-api no-longer follow nested schemesas result the talawa-admin got left behind. Also for more ref see/comment this [discussion](https://github.com/PalisadoesFoundation/talawa/discussions/1726) **Potential internship candidates** Please read this if you are planning to apply for a Palisadoes Foundation internship [PalisadoesFoundation/talawa#359](https://github.com/PalisadoesFoundation/talawa/issues/359)

I think there is a typo in the issue you created.
Do you mean  1. Make a membership request on private org from talawa-**admin**??

**Comment by Cioppolo14** [comment] 2023-12-29 01:41
@KrishavRajSingh This issue needs to be closed, as it is not in the correct repo.  I apologize for the error.

**Closed by Cioppolo14** 2023-12-29 01:41 UTC
Labels: bug
