### ISSUE TITLE
Bug Report When a new post is added, the latest post section in the organization's dashboard becomes distorted.

### ISSUE THREAD

**Issue by gauravsingh94** [PalisadoesFoundation/talawa-admin#1266] opened 2023-12-23 17:19 UTC
**Describe the bug**

When a new post is added, the latest section in the organization's dashboard becomes distorted.

**To Reproduce**

1. Go to any organization
2. Add some posts.
3. Go to dashboard.
4. In the lastest post section we can see the distorted design.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Pasted image](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/cda537df-4ce7-45e8-b08d-9b3d5050802d)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by gauravsingh94** [comment] 2023-12-23 17:25
Please assign this issue to me.

**Comment by aashimawadhwa** [comment] 2023-12-23 18:07
How are you planning to solve this? @gauravsingh94

**Comment by gauravsingh94** [comment] 2023-12-23 18:07
After the fix it will look like this.

file:///home/gaurav/Videos/Screencasts/Screencast%20from%202023-12-23%2023-35-55.webm

**Comment by gauravsingh94** [comment] 2023-12-23 18:08
After fix look like this

[Screencast from 2023-12-23 23-35-55.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/f80c6693-088b-48bc-a3cc-735e3c694dcf)

**Comment by gauravsingh94** [comment] 2023-12-23 18:11
> How are you planning to solve this? @gauravsingh94

or i can make it column when the card is very small

**Comment by Cioppolo14** [comment] 2023-12-24 13:42
@gauravsingh94  I have assigned you, but please get feedback from @aashimawadhwa on your proposed resolution before moving forward.

**Comment by gauravsingh94** [comment] 2023-12-24 14:48
> After fix look like this
> 
> [Screencast from 2023-12-23 23-35-55.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/f80c6693-088b-48bc-a3cc-735e3c694dcf)
> 

@aashimawadhwa Please provide your views on this.

**Comment by gauravsingh94** [comment] 2023-12-24 17:08
This is the design that I find most suitable for this scenario. When the post title is very long, it will break into two lines. However, if it exceeds two lines, we will use ellipsis (...) to indicate the overflow of text.

[Screencast from 2023-12-24 22-32-28.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/cfacebfd-f357-4d0c-940e-ac98d78ac663)



@aashimawadhwa  Please review this one.

**Comment by gauravsingh94** [comment] 2023-12-27 20:21
> This is the design that I find most suitable for this scenario. When the post title is very long, it will break into two lines. However, if it exceeds two lines, we will use ellipsis (...) to indicate the overflow of text.
> 
>  Screencast.from.2023-12-24.22-32-28.webm 
> @aashimawadhwa Please review this one.

@Cioppolo14  Please review this so that i can make pr

**Comment by rishav-devraj** [comment] 2024-01-03 19:09
@gauravsingh94 any change you make should be posted in PRs not issues. Increase the column width of the posts section

**Comment by palisadoes** [comment] 2024-01-21 03:02
Closing due to inactivity

**Comment by palisadoes** [comment] 2024-01-21 03:03
Is this issue still valid?

**Comment by Shyam-Raghuwanshi** [comment] 2024-01-21 12:15
Hi @palisadoes this is not a valid issue. I try to reproduce this issue but this not exist 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/94217498/7696ae5a-9032-41aa-94cb-a627ec6c49af)

**Comment by palisadoes** [comment] 2024-01-21 13:05
Thanks. Closing

**Closed** 2024-01-21 13:05 UTC
Labels: bug, feature request
