### ISSUE TITLE
App can only be accessed on `localhost`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1244] opened 2023-12-22 04:20 UTC
**Describe the bug**
1. The codebase hard codes localhost in many places
1. This means you cannot get Talawa-Admin to work while being accessed from a remote host without a proxy

**To Reproduce**

1. Install  Talawa-Admin on a remote system
1. Errors are seen when accessing the app directly from a remote host

**Expected behavior**
1. Access must be available from a remote host that is not located on `localhost`. This can only be truly tested when run from a completely different system.
1. The installation guide must show how to access Admin from a remote system
1. All hard coded instances of `localhost` must be replaced by configuration values in `.env`  and/or the browser URL where applicable

**Actual behavior**
- See screenshots

**Screenshots**

1. The `.env` file
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/ff04d0ac-6745-4d5d-8dc7-d903be892de4)
1. Devtools output
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/59c7ae9f-2f6e-4480-9738-7742a791a420)
1. The codebase hard codes localhost in many places
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/fbb2fe87-1aa7-4828-92cb-5c880d05502d)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RAGHAV-N5** [comment] 2023-12-22 04:30
I want to work on this issue please assign me this issue.

**Comment by monkCommits** [comment] 2023-12-22 09:43
Hey, I want to work on this issue.

**Comment by Sar-thak-3** [comment] 2023-12-22 13:56
Hi @palisadoes, I would love to work on this issue and make myself familiar with your project.

**Comment by monkCommits** [comment] 2023-12-23 10:24
Am thinking of testing this using a hypervisor (vmware). Do you recommend it, or should I test this on a totally different system? @Cioppolo14

**Comment by palisadoes** [comment] 2024-01-03 00:41
Unassigning due to no activity and no pull requests

**Comment by 1010varun** [comment] 2024-01-03 13:48
Hey, 
@palisadoes and @Cioppolo14 can you guys please tell me which service is being rendered on port 3005, is it the base URL. If so then it should be 3000. 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/104075461/2119e915-d3cf-44ed-87f0-45920ff09b49)

**Comment by palisadoes** [comment] 2024-01-04 00:30
Does the file path give you a clue?

**Comment by 1010varun** [comment] 2024-01-04 05:09
So, acc. to me it should be the base URL because these are some add-on support services, therefore it should be the base URL.

**Comment by 1010varun** [comment] 2024-01-05 06:47
@palisadoes, sir can you help me with this...

**Comment by palisadoes** [comment] 2024-01-05 12:14
Please discuss your potential options on the `#talawa-admin` slack channel. I'm tracking too many activities

**Comment by palisadoes** [comment] 2024-01-16 21:55
@1010varun 

We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories.

**Comment by 1010varun** [comment] 2024-01-17 06:04
@palisadoes,
Sorry sir for this, I will keep this in mind before raising any PR.

**Comment by palisadoes** [comment] 2024-01-30 20:47
@NayOoLwin5 

1. Your PR is causing Admin to fail. 
1. Your PR needs to be resubmitted without the failure occurring
1. You will need to write a test to make sure that the 400 errors don't happen again.

**Comment by palisadoes** [comment] 2024-01-30 21:12
@NayOoLwin5 

This may not be related to your work. We are troubleshooting.

**Comment by NayOoLwin5** [comment] 2024-01-31 06:58
Hi @palisadoes, does this issue still need to be opened? As the reporting issue is also closed and fixed. 

And that 400 bad request is just a ping to the server to check server health without any query. It reaches the server and returns 400 as the server only accepts POST method. The behavior is still working as expected when pinging to the server.
If you want to totally avoid the bad request error, need to add some query like user detail query with wrong data. Please let me know if that is the best approach or I shall leave same as it is for now.

**Comment by palisadoes** [comment] 2024-01-31 07:46
@NayOoLwin5 

1. Your PR didn't fix the fact that you can only access the app on localhost.
2. It will work if you run the API on your local system and configure Admin to use any IP address on your system.
1. Try running the API on a different system on your network. You can register, but you cannot log in.

Please resubmit a PR

**Comment by NayOoLwin5** [comment] 2024-02-07 15:17
Hi @palisadoes, currently the app can be accessed on remote system according to my test. In my test, I installed both Admin and API on the same remote system. Please check my test below

https://github.com/PalisadoesFoundation/talawa-admin/assets/52243229/7604c2e9-8c8e-4423-a318-a8436ea4b352

Do I still need to test by running the API on different remote host? Please let me know.

**Comment by NayOoLwin5** [comment] 2024-02-08 08:25
https://github.com/PalisadoesFoundation/talawa-admin/assets/52243229/d2ba6f36-a710-45fc-bdf7-e86aaed71fc1

I tested by installing API on completely different system too and it works fine. Am I missing something in reproducing the issue? API NODE_ENV is development. @palisadoes

**Comment by palisadoes** [comment] 2024-02-09 23:13
Please resubmit your PR and verify that this issue does not resurface
- https://github.com/PalisadoesFoundation/talawa-api/issues/1765

**Comment by palisadoes** [comment] 2024-02-29 22:32
Unassigning due to inactivity and an unsuitable PR solution

**Comment by aarishshahmohsin** [comment] 2024-03-04 14:24
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment] 2024-03-07 15:24
@palisadoes  @Olatade Currently the admin portal only works properly when the api and the admin are served on the same machine. 

To add support for remote hosts either the user should manually change the api endpoint to something like 
```http://remote_host:4000/graphql``` or the code automatically resolves. 

What approach should be followed? 

In the former approach the documentation would be updated to state this fact.

**Comment by palisadoes** [comment] 2024-03-07 15:58
1. How do you propose it would automatically resolve?
1. Documentation updates are expected
1. The setup script will need to be updated if required

**Comment by aarishshahmohsin** [comment] 2024-03-07 18:39
> 1. How do you propose it would automatically resolve?
> 1. Documentation updates are expected
> 1. The setup script will need to be updated if required

There would be a change in the api url if the admin is running remotely, but the api url contains "localhost". So the api URL will be modified from 
'http://localhost:4000/graphql' to 'http://remote_url:4000/graphql'

**Comment by palisadoes** [comment] 2024-03-07 21:07
Thanks

1. The app is broken as stated in the issue
2. You have verified it
3. Please fix it
4. Open a PR when ready without asking
5. Reviewers will be assigned when all the tests pass

Please take the initiative

**Comment by aarishshahmohsin** [comment] 2024-03-08 14:46
@palisadoes I have made the PR but There are 2 problems that occurred while working on the issue.
1. One problem occurring that needs to be fixed is the plugin store, which is coded incorrectly. in the src/components/AddOn/support/services/Plugin.helper.ts file.

```
    const result = await fetch(`http://localhost:${process.env.PORT}/store`);
    const result = await fetch(`http://localhost:3005/installed`);
```

are both fetching endpoints that do not exist and hence the addonstore component also does not work. 

2. The navbar button is not working on mobile devices.

Should I make issues for them?

**Comment by palisadoes** [comment] 2024-03-08 15:59
You don't need to ask permission to create issues

**Closed** 2024-03-11 01:57 UTC
Labels: bug
