### ISSUE TITLE
Bug Report - Search users' list by name doesn't work

### ISSUE THREAD

**Issue by Phyya** [PalisadoesFoundation/talawa-admin#613] opened 2023-03-09 15:45 UTC
**Describe the bug**
When logged in, searching for a user by name does not do anything. 

**To Reproduce**

1. Click on the  "Roles" navlink on the navbar.
2. Click on the input field and begin typing to search

**Expected behavior**
A list of users with names that include the letters searched should show up on the screen.

**Actual behavior**
Nothing happens.

**Screenshots**
![talawa-search-by-name](https://user-images.githubusercontent.com/80838239/224076427-560b00f8-2e50-45e9-8426-21016f7033bd.png)

**Additional details**
If it is a case where there is only supposed to be one user (not organization-wise), it will make sense to take the whole search feature away.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Phyya** [comment] 2023-03-09 15:45
Hello, kindly assign this issue to me. Thank you.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-10 02:14
hey @Phyya !
I noticed this too but if u press enter, it works! 
So its not like its not working..

**Comment by aviraldevv** [comment] 2023-03-10 12:25
@Phyya Please take a look properly this works. I appreciate you endeavour, but this needs issue should to be closed.
@palisadoes We can close this issue I have cross-checked for this functionality.

**Comment by Phyya** [comment] 2023-03-10 13:26
@aviraldevv I just pulled from the upstream and created a new branch. It still doesn't work. @palisadoes please confirm. Thank you.

**Comment by aviraldevv** [comment] 2023-03-10 13:32
@Phyya I can see your develop branch is 11 commits behind , please sync it to the latest updates .

![Screenshot_400](https://user-images.githubusercontent.com/121368112/224328929-3eb77f23-48dd-46a1-8f74-01872ea071c6.png)

**Comment by Phyya** [comment] 2023-03-10 13:33
Okay

**Comment by Pranauv-Kumar1803** [comment] 2023-03-15 15:50
Hey @Phyya... I noticed this too... so what's happening here is, if you search with a value which is not there in the first name, it doesn't do anything but if that value if present in the first name, it shows the correct user list.

I'm not sure if this is a bug or not.

@aviraldevv Please recheck and tell if I'm true or not!

**Comment by palisadoes** [comment] 2023-03-16 02:37
@Pranauv-Kumar1803 Wouldn't this be expected behaviour?

**Comment by palisadoes** [comment] 2023-03-16 02:38
Closing as this doesn't appear to be an issue.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-16 02:43
> @Pranauv-Kumar1803 Wouldn't this be expected behaviour?

I'm just asking that when you are searching by some value which is not present, wouldn't you show "no users found" as response as there are no users whose first name starts with that value?

**Comment by palisadoes** [comment] 2023-03-16 02:45
This looks like a duplicate of this issue and pull request.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/717

**Comment by Pranauv-Kumar1803** [comment] 2023-03-16 02:50
Yeah but nobody has implemented it in the Roles page. We can use the same reusable component here with some minor code changes.

**Comment by aviraldevv** [comment] 2023-03-17 02:33
@Phyya @Pranauv-Kumar1803 I cross-checked for the functionality it somewhat works but a better filter function would be definitely worth it with proper edge case handling.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-17 05:37
@aviraldevv Yeah a better filter function would be good

**Comment by palisadoes** [comment] 2023-03-17 06:11
@Phyya Are you still interested in working on this based on the comments?

**Comment by Pranauv-Kumar1803** [comment] 2023-03-17 13:28
Hey @palisadoes , if @Phyya isn't interested, can I try this?

**Comment by Pranauv-Kumar1803** [comment] 2023-03-17 16:43
I'll do the UserNotFound component adding and the filtering both in the same PR. Is that fine?

I'll have to wait for PostNotFound component's PR to get merged before I can do this.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-19 16:01
Hey @palisadoes !

yeah there's a small problem there... In that other PR, It's failing in one test and it says code coverage is 90.97% which is .67% less than expected..

I have tried lots to provide tests but still its dropping.. Can you help me with that?

**Comment by Pranauv-Kumar1803** [comment] 2023-03-19 16:01
> 1. Was the other PR merged?
> 2. Can you start on this now?

I have already started this and i just have to provide tests for this.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-19 16:04
Its just that I have another PR pending to merge because of one test where the code coverage drops by 0.6 % and I am unable to provide more tests. ( It's on the same component too ( Roles Page ) )

Can you help me with this?

**Comment by Pranauv-Kumar1803** [comment] 2023-03-24 06:51
Here's what I have done!

when there arent any users with the given input value, it shows like this : - 

![image](https://user-images.githubusercontent.com/97829544/227446442-8ca9973d-afa7-499d-b54f-1db665fcc164.png)

is this fine? I used the postNotFound component - changed the title and keyPrefix props of the postNotFound component to make this.. 

Does this look bad?

**Comment by aviraldevv** [comment] 2023-03-24 08:17
Hey @Pranauv-Kumar1803 make it `User not Found` seems like you have not updated the locales folder, figure out how to do so `Roles.Users` will be modified to just `User`.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-24 10:29
yeah thats what i thought too

**Comment by Pranauv-Kumar1803** [comment] 2023-03-24 11:21
hey i just have one doubt here... Doesn't i18next provide any auto translation so that we can convert the dynamic emails and names in the roles list? 

Because now, we literally provide all the translation in the locales folder and use them as keyPrefix... Isn't there any way to automate the translation itself?

**Comment by anshgoyalevil** [comment] 2023-03-24 11:39
@Pranauv-Kumar1803 

According to the best coding practices, we should not use dynamic translations for static texts. Why to waste a network call to call the translation api.

Also, emails and names are non mutable elements so they shouldn't be translated.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-24 11:42
Yeah that's true !

also I learnt that i18next doesn't have an automatic translation feature - i mean without providing the translations inside the locales folder..

**Comment by Pranauv-Kumar1803** [comment] 2023-03-24 12:18
Got it @palisadoes sir! Thanks!

**Comment by xoldyckk** [comment] 2023-03-24 13:38
@Pranauv-Kumar1803 Automatic translation is not child's play. You can't simply use dictionary translation for this task as each language is inherently different. Companies like facebook use complex machine learning algorithms and other specialized services to provide localised translation of content on their apps, and even that is not accurate enough.

**Comment by Pranauv-Kumar1803** [comment] 2023-03-24 13:44
Sorry if I asked something foolish.. 

I was just wondering if i18next provides auto translation as a service or not.

Got it @xoldyckk, Thanks!

**Closed** 2023-04-12 03:09 UTC
Labels: bug, no-issue-activity
