### ISSUE TITLE
Bug Report: User Role Not Displaying in 'People' Section

### ISSUE THREAD

**Issue by aditya-bansal-7** [PalisadoesFoundation/talawa-admin#2455] opened 2024-11-19 21:31 UTC
**Describe the bug**
In the 'People' section of the Talawa User Portal, the "Role" column does not display any roles for the users in some cases (as shown in the first screenshot). This is inconsistent with other organizations where roles such as "Superadmin" or "User" are properly displayed (refer to the second screenshot).

**To Reproduce**

1. Log in to the Talawa User Portal.
2. Navigate to the 'People' section in an organization (e.g., Unity Foundation).
3. Observe the "Role" column — roles are missing for all users.

**Expected behavior**
The "Role/User-Type" column should display the correct role (e.g., Admin, Superadmin, User) for each user in the table.

**Actual behavior**
The "Role/User-Type" column is empty, leaving users and admins without role visibility

**Screenshots**
Screenshot 1: (Role missing)
![image](https://github.com/user-attachments/assets/6c708532-423d-41be-ba05-9dfccf993db7)
Screenshot 2: (Role displayed correctly)
![image](https://github.com/user-attachments/assets/8fdae316-ec6a-48da-80a0-6c9e41bbf58e)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by dev-mayanktiwari** [comment] 2024-11-24 13:50
Hey can i work on this issue?

**Comment by aditya-bansal-7** [comment] 2024-11-24 14:32
I am already working on this.

**Comment by AryanSwaroop** [comment] 2024-12-01 12:14
can you assign this issue to me !!

**Comment by AryanSwaroop** [comment] 2024-12-01 14:47
Thanks i'll start working

**Comment by AryanSwaroop** [comment] 2024-12-14 09:00
found that issue was with an interface , changing that fixed issue but at the time of commit error occured as commit test were ran.
should i find some other solution ? or change the test script. 

@palisadoes

**Comment by AryanSwaroop** [comment] 2024-12-15 05:57
I found that changing interface could help but commiting it is causing error ! Should i change test script or find some other solution ! 

@palisadoes

**Comment by palisadoes** [comment] 2024-12-15 14:59
Update the tests to validate the expected performance of your changes to the source code.

**Comment by AryanSwaroop** [comment] 2024-12-16 07:13
ok

**Comment by AryanSwaroop** [comment] 2024-12-22 08:39
@raggettii i have solved the same , doing changes in test now.

**Comment by gurramkarthiknetha** [comment] 2024-12-25 05:07
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by palisadoes** [comment] 2024-12-25 05:13
> If no one is currently working on this issue, I would like to take it on. Please assign it to me.

@gurramkarthiknetha 

Please don't ask to be assigned if:

1. the issue is assigned, or 
2. inactive, but with a pending PR 

Everyone needs a chance to participate

**Comment by gurramkarthiknetha** [comment] 2024-12-25 05:15
> > If no one is currently working on this issue, I would like to take it on. Please assign it to me.
> 
> @gurramkarthiknetha
> 
> Please don't ask to be assigned if:
> 
> 1. the issue is assigned, or
> 2. inactive, but with a pending PR
> 
> Everyone needs a chance to participate

Got it, sorry about that! I'll keep it in mind and make sure to give others a fair chance to participate. Thank you for clarifying!

**Closed** 2024-12-31 14:36 UTC
Labels: bug
