### ISSUE TITLE
Not getting users on role and request page

### ISSUE THREAD

**Issue by VenomFate-619** [PalisadoesFoundation/talawa-admin#371] opened 2023-01-02 05:07 UTC
**Describe the bug**
Not getting users on the role and request page. I had already added users.
The network request on the role and request page is falling with 400 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the requests or role page
2. No user will be there in the table
3. Check the network tab, the request failed

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/210196615-c6ef1fc7-a161-4755-a6a9-b93d294d5f92.png)

**Additional details**
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1672326451668909?thread_ts=1671211363.752999&cid=C01RPC00K0D
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1672327119525069

**Comment by VenomFate-619** [comment] 2023-01-02 05:08
I would like to resolve this.

**Comment by VenomFate-619** [comment] 2023-01-02 05:08
I would like to resolve this @yasharth291 .

**Comment by prathamesh-mutkure** [comment] 2023-02-05 11:37
Hi @noman2002 @palisadoes, there seems to be no activity on this issue for over a month, can I work on this?

**Comment by palisadoes** [comment] 2023-02-05 16:46
@VenomFate-619 You have two open issues. I'll assign to someone else

**Comment by prathamesh-mutkure** [comment] 2023-02-09 18:40
Hey @palisadoes @noman2002, as suggested by @VenomFate-619, I checked the code and found out that the problem is the `spamInOrganizations` query inside User in frontend but it is absent in the type definitions in the backend.

Frontend definitions: https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/GraphQl/Queries/Queries.ts#L78

Backend definitions: https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/typeDefs/user/user.ts#L3

We have two ways to fix this -

- Remove the `spamInOrganizations` from frontend which fixes the issue
- Add `spamInOrganizations` query in backend 

Which approach should we follow? I guess the best thing to do for now is to comment the code causing error until it is fixed from backend

**Comment by prathamesh-mutkure** [comment] 2023-02-09 19:04
Okay, this seems to be a much bigger issue than what it looks like

The `USER_LIST` query which is causing issues is also used in other pages which include

- `AddOnStore`
- `BlockUser`
- `OrganizationPeople`
- `Request`
- `Roles`

Fixing this query will likely resolve many other issues like some pages just refresh/redirect due to graphql query errors.

**Comment by anshgoyalevil** [comment] 2023-02-10 07:45
@palisadoes I just checked out the Talawa-API's previous pull requests, and this issue is related to the PR https://github.com/PalisadoesFoundation/talawa-api/pull/826 and PR https://github.com/PalisadoesFoundation/talawa-api/pull/742

Why the code for these PR's is not there in Talawa-API Project?

**Comment by palisadoes** [comment] 2023-02-10 16:16
1. We converted TalawaAPI from `node.js` to `Typescript` for GSoC 2022. This helped to standardize the Talawa code base languages and tools. 
1. The PR was against our old `develop_legacy` branch which used `node.js`. 
1. We have a GSoC 2023 idea that we hope will restore [spam mitigation as a plugin](https://docs.talawa.io/docs/internships/internship-ideas#creating-new-features-and-refactoring-existing-features-into-plugins).

**Comment by palisadoes** [comment] 2023-02-10 16:22
We'll need need to fix the tests. About how many would fail?

**Comment by palisadoes** [comment] 2023-02-10 16:22
Let's chat on slack

**Comment by palisadoes** [comment] 2023-02-10 16:26
@prathamesh-mutkure Please make the modifications and fix the resulting failing tests in this PR

**Comment by prathamesh-mutkure** [comment] 2023-02-10 16:36
Sure, I'll make the changes

**Closed** 2023-02-13 12:39 UTC
Labels: bug
