### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-admin#513] opened 2023-02-26 15:20 UTC
**Describe the bug**
The screen stays on creating organization modal after the organization is created

**To Reproduce**

1. signup/login
2. treat yourself as SUPERADMIN
3. Click on the button Create Organization
4. Simply create the new organization

**Expected behavior**
When an organization is created, the modal should ideally be closed and it should be navigated to the manage oranizations section.

**Actual behavior**
The screen stays on creating organization modal after the organization is created

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/221419645-fa78465d-236a-4f9a-99e3-d8ca380158e2.png)

**Additional details**
Not required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishant3721** [comment] 2023-02-26 15:20
@palisadoes I would like to work on it

**Comment by aashimawadhwa** [comment] 2023-02-26 15:21
I cannot see this issue on my system is it so for you @xoldyckk .

**Comment by rishav-jha-mech** [comment] 2023-02-26 15:31
@aashimawadhwa i also noticed this issue, when you successfully create an organisation, you will be shown a toast and then the createOrganisation form in modal will become empty and you have to manually close it by clicking on the cross button.

I suggest it would be better if the modal is closed once the organisation is created.

**Comment by nishant3721** [comment] 2023-02-26 15:44
@rishav-jha-mech Absolutely right

**Comment by xoldyckk** [comment] 2023-02-26 15:58
> I cannot see this issue on my system is it so for you @xoldyckk .

It's not a bug. It's a UI behaviour. You can choose what you want to do after an organization is created.

**Comment by nishant3721** [comment] 2023-02-26 16:13
@xoldyckk wouldn't it be better if modal closed after creating an organisation successfully, such that it will be more friendly to the user!?

**Comment by xoldyckk** [comment] 2023-02-26 16:57
> @xoldyckk wouldn't it be better if modal closed after creating an organisation successfully, such that it will be more friendly to the user!?

Yeah it will be more user friendly, but only if the user is on the organization list page when creating the organization. If user is on some other page, and there's still the option to create organization, and you reroute them back to organization list page on creation then it's bad.

**Comment by nishant3721** [comment] 2023-02-26 19:46
@xoldyckk Then, the modal should be closed simply, If the user is on the organisation list page then, creating an organisation will be routed back to the list page, in other cases it would stay on that page even after creating the modal.

**Comment by xoldyckk** [comment] 2023-02-26 20:05
> @xoldyckk Then, the modal should be closed simply, If the user is on the organisation list page then, creating an organisation will be routed back to the list page, in other cases it would stay on that page even after creating the modal.

Yeah. So, you you want to assigned for this?

**Comment by palisadoes** [comment] 2023-02-26 20:50
On what other page besides the organization list page can creating an organization be done?

**Comment by nishant3721** [comment] 2023-02-27 02:44
> > @xoldyckk Then, the modal should be closed simply, If the user is on the organisation list page then, creating an organisation will be routed back to the list page, in other cases it would stay on that page even after creating the modal.
> 
> Yeah. So, you want to get assigned for this?

Yes

**Closed** 2023-02-28 03:13 UTC
Labels: feature request
