### ISSUE TITLE
[userTypeFix] Blank screen encountered in Plugin Store 'Installed' tab when accessed as super admin.

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1764] opened 2024-03-23 15:40 UTC
**Describe the bug**
Upon logging in as a super admin and selecting any organization from the list, navigating to the 'Installed' tab within the Plugin Store's settings results in a blank screen.

**To Reproduce**
1. Log in as a super admin.
2. Select any organization from the list.
3. Go to the Plugin Settings.
4. Select the 'Installed' tab.

**Expected behavior**
The 'Installed' tab within the Plugin Store should display the list of installed plugins for the selected organization.

**Actual behavior**
The 'Installed' tab shows a blank screen, preventing the display of installed plugins.

**Screenshots**
<img width="1206" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/9a4ef9fa-6b72-43c9-b807-556c922d3f3d">

**Additional details**
[Add any other relevant context or details about the bug here]

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment] 2024-03-23 17:29
@palisadoes I think it is a duplicate of 

- #1754 

Maybe close #1754  and let others work here

**Closed** 2024-03-23 17:33 UTC
Labels: bug, good first issue, unapproved, userTypeFix, GSoC Priority
