### ISSUE TITLE
Deprecation warning after running the development server

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1496] opened 2024-01-25 11:25 UTC
**Describe the bug**
When the command ```npm run serve``` is executed to run the dev server, deprecation warnings are shown.

**To Reproduce**

1. Install the packages
2. Run ```npm run serve```

**Expected behavior**
There should be no warnings

**Actual behavior**
'onAfterSetupMiddleware' and 'onBeforeSetupMiddleware' are deprecated

**Screenshots**
![image (copy 1)](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/4e65f63f-eb54-45a2-a2d3-f87aa9cf8b74)

**Additional details**

**Comment by pushkar707** [comment] 2024-01-26 16:23
I also see this warning. @palisadoes, can you please assign this issue to me once its approved

**Comment by varshith257** [comment] 2024-01-27 03:30
@aarishshahmohsin The Same has been reproduced but It's working fine with the latest version of nodejs

**Comment by pushkar707** [comment] 2024-01-27 20:12
Thanks for assigning me the isse, I will quickly resolve it

**Comment by pushkar707** [comment] 2024-01-28 08:59
This is an issue with react-scripts dependency. We can solve this issue by manually changing a config file within react scripts,

**Comment by palisadoes** [comment] 2024-01-28 09:01
If you have a solution, please open a PR

**Comment by pushkar707** [comment] 2024-01-28 09:11
The solution requires me to modify the node_modules. That's the point

**Comment by Cioppolo14** [comment] 2024-02-08 02:27
Unassigning due to no activity or PR.

**Comment by dhruvgupta0503** [comment] 2024-02-13 10:31
Can I work on this issue, Pls assign it to me

**Comment by Cioppolo14** [comment] 2024-02-24 01:13
Unassigning due to no activity or open PR.

**Comment by AdityaRaimec22** [comment] 2024-02-24 04:39
Can I get assigned to the issue.

**Comment by rohansx** [comment] 2024-02-24 11:08
Is this issue still persist, if it is there then I would like to take on this task?

**Comment by pranshugupta54** [comment] 2024-03-01 21:51
`npm run serve` works fine for me though (`develop` branch)


<img width="737" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/a8812a69-08d6-4b86-ba21-4d9010f7cfbd">

**Comment by Cioppolo14** [comment] 2024-03-02 00:32
@rohansx I am still seeing the deprecated warning, do you see it when you start talawa-admin?

**Comment by antriksh-9** [comment] 2024-03-05 20:03
Hey @Cioppolo14 I want to work on this issue.
Please assign it to me.

**Comment by dhruvgupta0503** [comment] 2024-03-30 08:08
Hi Can I get this issue assigned

**Comment by palisadoes** [comment] 2024-07-25 21:01
unassigning. no activity

**Comment by PurnenduMIshra129th** [comment] 2024-11-15 14:24
can i work on this issue? plz assign me.I would love to work on it.

**Closed** 2024-11-16 22:38 UTC
Labels: bug, no-issue-activity
