### ISSUE TITLE
Bug Report: ReCaptcha fails when trying to login using superadmin user

### ISSUE THREAD

**Issue by ssarkar551** [PalisadoesFoundation/talawa-admin#1468] opened 2024-01-21 18:16 UTC
**When trying to sign in using a superadmin user, reCAPTCHA fails.**

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/46297022/351681cb-2613-4227-a965-e2a85ebbeef1)

1.Select a superadmin user to login with
2. Enter username and password.
3. Click on the reCAPTCHA check box
4.  Login

**Expected behavior**
Super admin user should be able to login as usual and view the admin dashboard.
**Actual behavior**
Super admin users are unable to login, unless reCAPTCHA is removed from .env file.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ssarkar551** [comment] 2024-01-21 18:42
This is my first issue, and I would really like to contribute more by working on this issue as well.

**Comment by noman2002** [comment] 2024-01-22 10:04
@ssarkar551 There is some issue with your installation. Have you followed the steps correctly ?

**Comment by ssarkar551** [comment] 2024-01-22 19:07
@noman2002 yes I did. I also had a chat with some other people on the talawa-admin slack channel, where another user pointed out this same problem as well

**Comment by noman2002** [comment] 2024-01-23 08:58
@beingnoble03 Please verify if this issue exists or not and assign if exists.

**Comment by pushkar707** [comment] 2024-01-26 16:28
@ssarkar551 , I am also having this same issue

**Comment by varshith257** [comment] 2024-01-27 03:28
@noman2002 
This issue has to be addressed. Seen a lot of new contributors facing the same issue as pointed here while setting up the talawa-admin

**Comment by varshith257** [comment] 2024-01-27 05:47
@palisadoes   
Make it an urgent fix as even most of my friends approached me regarding this issue and most of the new contributors also pointed out the same issue on Slack while doing the setup of talawa-admin.
The same error has been reproduced in a new system while I am doing the setup of talawa-admin.

I have added the console log to check its behaviour:

`      console.log('reCAPTCHA verification result:', data.recaptcha); 
`
The console resulted:

`reCAPTCHA verification result: false `

The possible root cause is either reading of SITE KEY from the .env file or verification code logic error

**Comment by ssarkar551** [comment] 2024-01-29 07:57
@varshith257 
I have been trying to figure out the problem, the `recaptchaToken` that is getting passed to the `verifyRecaptcha` method, is coming as void.  I also added console logs to verify this: `recaptcha token: `.
Trying to figure out the root cause of this issue.

**Comment by varshith257** [comment] 2024-02-05 15:57
@ssarkar551 Have you got the root cause for it?

**Comment by Cioppolo14** [comment] 2024-02-17 01:26
@ssarkar551 Are you working on this still? If not, we will reassign tomorrow.

**Comment by ssarkar551** [comment] 2024-02-17 06:04
@Cioppolo14 hey, sorry I tried to fix this issue but couldn't do so. Please reassign

**Comment by GlenDsza** [comment] 2024-02-17 07:53
I would like to work on this issue
I have resolved the issue on my local

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/4d758ce1-6a42-41c7-a44a-8fc2be6f3603

**Closed** 2024-03-04 07:28 UTC
Labels: bug, no-issue-activity
