### ISSUE TITLE
Code Coverage: Create tests for src/components/UserPortal/Login/Login.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1032] opened 2023-11-05 16:13 UTC
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by MahendraDani** [comment] 2023-11-28 05:56
I read the current tests in [Login.test.tsx](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/components/UserPortal/Login/Login.test.tsx) and observed the current [code coverage](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src%2Fcomponents%2FUserPortal%2FLogin%2FLogin.tsx). 
We can observe that codecov says only lines 54 and 55 are not covered in the tests : 
https://github.com/PalisadoesFoundation/talawa-admin/blob/d8e6a7d26dc5bbc8c8b06456d6367314fe088dfc/src/components/UserPortal/Login/Login.tsx#L54-L55

After trying all the possible case locally I found out that  the control does not reach on the above lines in any cases. In other words when `handleLogin` function is triggered with non-empty `email` and `password` fields the `data` will always be returned and hence the else condition (when `data` is empty as returned by login mutation) never occurs.

Thus to get the test coverage of this component to 100% is to simply remove the else condition i.e
https://github.com/PalisadoesFoundation/talawa-admin/blob/d8e6a7d26dc5bbc8c8b06456d6367314fe088dfc/src/components/UserPortal/Login/Login.tsx#L54-L55

It does not break the functioning of **user portal** and the test coverage also reaches to **100%**.
Please let me know if this approach is correct or there is something else need to be done?
I would like to work on this issue

cc : @noman2002

**Comment by noman2002** [comment] 2023-11-28 06:04
Try to mock the situation in which it goes to the else condition. And write the test for the same. Removing the else condition will not be a good approach.

**Comment by MahendraDani** [comment] 2023-11-28 06:05
> Try to mock the situation in which it goes to the else condition. And write the test for the same. Removing the else condition will not be a good approach.

I will try

**Comment by MahendraDani** [comment] 2023-11-29 04:20
@noman2002 
Are **admins** and **superadmin** allowed to login into `user portal`?
Because when I was trying to mock all possible situations I found that we can login into user portal using **admin** or **superadmin** credentails.

### Steps to reproduce
1. Go to user portal - localhost:3000/user 
2. Enter credentials of admins or superadmins
3. Click on Login button.
4. You will be logged into user portal as admin or superadmin

**Comment by MahendraDani** [comment] 2023-11-30 03:15
@noman2002 
I am not able to mock the situation in which the else statement is executed.
Would you please help?

**Comment by MahendraDani** [comment] 2023-12-05 13:37
> @noman2002 I have tried all possible mocks and I have represented the outputs in the form of a [diagram](https://app.eraser.io/workspace/bnxixe5oeTAiVZg5aOeY?origin=share).
> 
> Please observe from the diagram that there are only three possible cases when any person tries to login into user portal `http://localhost:3000/user`:
> 
> * With no credentials i.e person clicks `login` button without entering `email` and `password` then they are responded with error toast message `Please enter a valid password and email`.
> * When person is either `user`,`admin` or `superadmin` they are logged into user portal succcessfully.
> * When person tries to login with credentials which are not in database then the response is a error toast with message `User not found`.
> 
> > Note that all the above cases are already covered in the current tests.
> 
> We can observe that there is no other case than this in which control will execute [line 54 and 55](%5Btalawa-admin/src/components/UserPortal/Login/Login.tsx%5D(https://github.com/PalisadoesFoundation/talawa-admin/blob/d8e6a7d26dc5bbc8c8b06456d6367314fe088dfc/src/components/UserPortal/Login/Login.tsx#L54-L55))
> 
> What do you think? If there is anything that I missed please help me through. Thanks

@noman2002 Any suggestions?

**Comment by palisadoes** [comment] 2023-12-16 01:51
Unassigning due to inactivity and no related PR

**Comment by pateldivyesh1323** [comment] 2023-12-16 09:35
@noman2002, @palisadoes I would like to work on this.

**Comment by pateldivyesh1323** [comment] 2023-12-23 08:50
I am unassigning myself, this is now up for grabs.

**Comment by shankeleven** [comment] 2024-01-05 04:24
please assign the issue to me

**Comment by Shashankpantiitbhilai** [comment] 2024-01-15 10:49
I am interested,please assign this to me

**Comment by Cioppolo14** [comment] 2024-01-15 13:53
@shankeleven Sorry I missed this earlier! You currently have 2 issues in another repo, so I am going to assign it to @Shashankpantiitbhilai.

**Comment by Shashankpantiitbhilai** [comment] 2024-01-16 12:29
Thanks for assigning

**Comment by Cioppolo14** [comment] 2024-01-27 01:07
Unassigning due to inactivity.

**Comment by Sauradip07** [comment] 2024-01-28 10:42
Please assign me I want to work on this issue

**Comment by Cioppolo14** [comment] 2024-01-28 14:36
@Sauradip07 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by gautam-divyanshu** [comment] 2024-01-31 18:39
Please assign me this issue , love to work on it.

**Comment by gautam-divyanshu** [comment] 2024-02-02 10:23
> Please assign me this issue , love to work on it.
I am working on it.

**Comment by karthxk07** [comment] 2024-02-09 13:22
@palisadoes Sir, Is this issue still open and stale? I can work on this.

**Comment by shankeleven** [comment] 2024-02-20 16:14
assign this issue to me @palisadoes 
would love to work on this

**Comment by Cioppolo14** [comment] 2024-03-04 01:20
Unassigning due to no activity.

**Comment by pranshugupta54** [comment] 2024-03-11 17:51
Hey @Cioppolo14, @palisadoes. Is this completed?

[Coverage looks 100%](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src%2Fcomponents%2FUserPortal%2FLogin%2FLogin.tsx)

<img width="1355" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/a612b45f-0e40-41ef-bfb4-2f409f11d94d">

**Closed** 2024-03-11 18:06 UTC
Labels: good first issue, test
