### ISSUE TITLE
communityProfile route accessible to users

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-admin#1803] opened 2024-03-25 20:26 UTC
**Describe the bug**
`communityProfile` route accessible to users even though they are not authorised to do so.

**To Reproduce**

1. Log in as user
2. Modify and change the endpoint to `communityProfile`

**Expected behavior**
Endpoint validation should be performed before accessing any route

https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/2b8814f8-345c-47ff-aad3-775953c631a1

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment] 2024-04-11 05:10
@krishna619, are you still facing this issue. I cannot reproduce this issue. This issue can be closed.

**Comment by Cioppolo14** [comment] 2024-04-11 12:41
I am closing.  Please tag me if it needs to be reopened.

**Closed by Cioppolo14** 2024-04-11 12:41 UTC
Labels: bug, unapproved, feature request, no-issue-activity
