### ISSUE TITLE
Admin - Remove Support for Private Organizations

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1327] opened 2023-12-30 22:00 UTC
**Is your feature request related to a problem? Please describe.**
We need to reduce and simplify some of the Talawa features. 

The concept of private organizations is unlikely given that most organizations using Talawa will be non-profits where transparency will be important.

Therefore not just must the organizations be always public. They must also always be visible.

**Describe the solution you'd like**

Remove all support for private organizations in:
1. Sections of screens that contain references this feature
1. Any screens completely dedicated to this feature
1. All supporting code

Other:

1. All tests must be valid and pass
1. No other functionality must be affected.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1604
2. https://github.com/PalisadoesFoundation/talawa-admin/issues/1327
3. https://github.com/PalisadoesFoundation/talawa/issues/2287

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment] 2023-12-31 08:12
I would love to work on this issue : )

**Comment by aialok** [comment] 2024-01-02 10:58
![ispublic](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/87c06184-170a-4970-b565-5edaba45543e)

- To be more clear about the given issue, I want to know in the above given picutres I need to remove `isPublic` functionality from the create Organisation modal ?

**Comment by palisadoes** [comment] 2024-01-02 12:35
Please read the issue thoroughly

**Comment by palisadoes** [comment] 2024-01-07 05:13
Please refer to this discussion before proceeding
- https://github.com/PalisadoesFoundation/talawa-api/pull/1643#issuecomment-1879947274

**Comment by palisadoes** [comment] 2024-01-11 21:36
FYI - The issue blocking this has been completed
- https://github.com/PalisadoesFoundation/talawa-api/issues/1604

**Comment by palisadoes** [comment] 2024-01-14 17:32
Reopening because the introspection test in the previous PR failed.

@aialok please submit a follow up PR to fix this

**Comment by aialok** [comment] 2024-01-14 19:31
Hey @palisadoes, I checked why the test failed and found the issue in the `talawa-api` repository, not `talawa-admin`. The problem is that the workflow is cloning the `main` branch of `talawa-api`, in which schema.graphql is not up to date as changes are done in develop branch, because of this isPublic is not updated with userRegistrationRequired in schema.graphql, causing the test to fail.

Here's the workflow file:

![Workflow File](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/172b1328-54f5-4234-baea-83c2bc6ed7f3)

Here's the `schema.graphql` file:

![Schema.graphql](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/785cd845-155d-44e1-8162-f9c8fe5698be)

And the failing GraphQL inspector:

![Failing GraphQL Inspector](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/d7bb8707-76d8-448e-ba1b-ef5e9667b22e)

**Comment by palisadoes** [comment] 2024-01-14 20:09
@aialok How can we clone the `develop` branch instead?

**Comment by palisadoes** [comment] 2024-01-14 20:11
I'll open an issue to fix this. The action needs to checkout the `develop` branch after cloning

**Comment by aialok** [comment] 2024-01-14 20:14
> I'll open an issue to fix this. The action needs to checkout the `develop` branch after cloning

Yeah or we can use directly 'git clone -b branch_name --single-branch https://github.com/username/repository.git'

**Comment by palisadoes** [comment] 2024-01-14 20:16
The branch name needs to match in both repos so that it doesn't break in `main` when we do merges from `develop`.

**Comment by aialok** [comment] 2024-01-14 20:38
> The branch name needs to match in both repos so that it doesn't break in `main` when we do merges from `develop`.

I need some time to research about  how to render dynamically branch name.
I will fix this issue by today afternoon (Indian standard time).

**Comment by palisadoes** [comment] 2024-01-14 20:45
> > The branch name needs to match in both repos so that it doesn't break in `main` when we do merges from `develop`.
> 
> I need some time to research about how to render dynamically branch name. I will fix this issue by today afternoon (Indian standard time).

Ask to be assigned the issue #1429. Issues cannot be assigned to people not participating in the comments section

**Comment by aialok** [comment] 2024-01-21 04:16
> The branch name needs to match in both repos so that it doesn't break in `main` when we do merges from `develop`.

    @palisadoes please close this issue as it is completed.

**Closed** 2024-01-21 06:56 UTC
Labels: feature request
