### ISSUE TITLE
changes in the Setting feature of Update Organization

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-admin#485] opened 2023-02-19 09:15 UTC
**Is your feature request related to a problem? Please describe.**
We have a setting page to update Organization details. In that, there is an Option to fill App Language Code.
![Screenshot from 2023-02-19 14-30-51](https://user-images.githubusercontent.com/58592306/219939279-55eecd08-d3db-4805-bd04-74ca18dd9353.png)
We want to have a dropdown for the language option just like this one.
![Screenshot from 2023-02-19 14-36-19](https://user-images.githubusercontent.com/58592306/219939320-45815b33-38ab-4d38-9e73-be0f978cd0a1.png)

**Describe the solution you'd like**
Add a DropDown to choose the App Language Code.

**Approach to be followed (optional)**
we want to minimize changes to the existing design. Hence no new CSS, no new responsive design, just the enabling of previously disabled or incorrectly implemented features.

**Comment by rishav-jha-mech** [comment] 2023-02-19 09:51
I can work on this issue please assign it to me once its approved.

**Comment by palisadoes** [comment] 2023-02-19 16:25
You must also complete tests for the work done. Or code coverage cannot decline

**Comment by palisadoes** [comment] 2023-02-19 16:27
You must also complete tests for the work done. Our code coverage cannot decline

**Comment by anikdhabal** [comment] 2023-02-19 18:33
can i work on this?

**Comment by noman2002** [comment] 2023-02-19 18:47
@anikdhabal This is already assigned to someone. Please look at other issues and comment on it to get it assigned to you.

**Comment by anikdhabal** [comment] 2023-02-19 19:01
@noman2002 what if i make a pull request before someone ,who has assigned?

**Comment by palisadoes** [comment] 2023-02-19 19:46
> @noman2002 what if i make a pull request before someone ,who has assigned?

It will be closed immediately. We only review PRs where the submitter has been approved to work on the issue, and the issue is mentioned in the PR.

**Comment by rishav-jha-mech** [comment] 2023-02-20 11:41
@tasneemkoushar  there's no code written for mutation of App Language Code , that means we are not sending the data regarding App Language Code to the UPDATE_USER_MUTATION, so i looked into talawa-api repo, its recieving only these params from the frontend

input UpdateUserInput {
    firstName: String
    lastName: String
    email: String
  }
So should i update the mutation to include App Language Code ? (But then talawa-api needs to be updated or the appLanguageCode will not be stored), or leave it as it is (Because password, usertype and display image is also not being sent to the backend, so it will not make much of a difference if app language code is not sent.)?

**Comment by palisadoes** [comment] 2023-02-20 13:21
- Please create an issue for the API with the mutation modifications you need for this to work. 
- Tie it to this issue.
- You or someone else can work on getting this prerequisite done

**Comment by rishav-jha-mech** [comment] 2023-02-22 15:22
I have completed the feature, but the in place of dropdown i have used the select tag of form and have written tests for it, should i create a PR ?

**Comment by rishav-jha-mech** [comment] 2023-02-23 00:04
![Image 1](https://user-images.githubusercontent.com/76212518/220791080-2d91e576-3b9e-4cf2-8b77-09ff4cec97d7.png)
![Image 2](https://user-images.githubusercontent.com/76212518/220791863-d220624c-fbbc-486f-8f22-89efa8871069.jpg)

**Comment by palisadoes** [comment] 2023-02-23 00:18
OK, go ahead. Just submit the PR next time and the discussion can happen there.

**Closed** 2023-02-25 20:05 UTC
Labels: feature request, gsoc
