### ISSUE TITLE
Fix custom field on settings page

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1152] opened 2023-12-07 14:03 UTC
**Describe the bug**
Response not successful: Received status code 400  is rendered in custom fields in the settings page

**To Reproduce**

1. click on manage form the org list screen
2.  click on settings
3. see the error

**Expected behavior**
custom fields of the organization should be displayed

**Actual behavior**
Response not successful: Received status code 400  is rendered in custom fields in the settings page

**Screenshots**
![Screenshot 2023-12-07 at 7 26 45 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/b3ef30bd-5ea2-4adf-a40c-a48d594bfa35)

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by racky7** [comment] 2023-12-07 14:06
Please assign this to me.

**Comment by racky7** [comment] 2023-12-07 14:32
@aashimawadhwa I am unable to reproduce this bug.
<img width="1440" alt="Screenshot 2023-12-07 at 7 59 04 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/74532684/401f5d47-39e8-435e-a02d-255a6c14dbac">

**Comment by palisadoes** [comment] 2023-12-07 17:49
> @rishav-jha-mech can you re-check this.?

You can see it here in the video:
- https://youtu.be/9ppDJMhoXac?t=2307

**Comment by racky7** [comment] 2023-12-08 06:39
I am still unable to reproduce the bug. It's working as expected. 
<img width="1439" alt="Screenshot 2023-12-08 at 12 08 48 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/74532684/10f51b02-4a17-4bb4-8658-bea4ae60c258">

**Comment by palisadoes** [comment] 2023-12-08 23:43
@racky7 Have you tried adding any custom fields? If you don't have any then you may not see the issue

**Comment by racky7** [comment] 2023-12-09 04:57
@palisadoes Yes I have tried adding the custom field.

**Comment by pateldivyesh1323** [comment] 2023-12-09 09:29
@palisadoes Yes this is working fine.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/01fd0ec9-293e-4db9-993b-3ceee2a65537)

**Comment by palisadoes** [comment] 2023-12-09 13:01
Thanks. Closing

**Closed** 2023-12-09 13:02 UTC
Labels: bug
