### ISSUE TITLE
USER REDESIGN: redesign the Profile Settings screen for the talawa user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1512] opened 2024-01-28 17:48 UTC
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the Profile Settings screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.
current situation :
![Screenshot 2024-01-28 at 11 15 38 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/d552397a-fcaf-4f0b-a360-c08d6ba17494)
Desired Result:
![Screenshot 2024-01-28 at 11 15 14 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/5128787d-aa13-4f2d-9c08-9a266f169b19)

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : #1510 (sidenavbar is covered in this issue)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by its-VinayKumar** [comment] 2024-01-28 17:54
Hello! @aashimawadhwa can I work on this plz.

**Comment by takshakmudgal** [comment] 2024-01-28 18:23
I'd like to work on this issue.

**Comment by aashimawadhwa** [comment] 2024-01-28 18:27
@its-VinayKumar  assigned 👍🏼

**Comment by Cioppolo14** [comment] 2024-02-08 02:22
Unassigning due to no activity or open PR.

**Comment by varshith257** [comment] 2024-02-08 02:32
I would like to work on this issue

**Comment by NayOoLwin5** [comment] 2024-02-08 03:14
I would like to work on this.

**Comment by its-VinayKumar** [comment] 2024-02-08 03:43
@Cioppolo14 Plz Reassign me, the issue work in progress.

**Comment by its-VinayKumar** [comment] 2024-02-08 03:44
@aashimawadhwa Plz Reassign me, the issue work in progress.

**Comment by Cioppolo14** [comment] 2024-02-08 12:25
@its-VinayKumar I am reassigning. How long will it take to have a PR.

**Comment by rahulch07** [comment] 2024-02-19 20:30
@Cioppolo14 I would like to work on this.

**Comment by Cioppolo14** [comment] 2024-02-20 00:34
@its-VinayKumar Are you still working on this?

**Comment by its-VinayKumar** [comment] 2024-02-20 04:31
@Cioppolo14 Yes, I am still working on this and definitely make PR soon.

**Comment by its-VinayKumar** [comment] 2024-02-26 13:30
@git-init-priyanshu I am working on this issue. :)

**Comment by akhilender-bongirwar** [comment] 2024-03-02 16:01
@its-VinayKumar, it has been more than a month since the issue is assigned to you. Are you still working on this issue?

// @Cioppolo14

**Comment by palisadoes** [comment] 2024-03-02 16:06
Unassigning due to inactivity

**Comment by disha1202** [comment] 2024-03-02 16:09
Hi 
I would like to work on this.

**Comment by akhilender-bongirwar** [comment] 2024-03-02 16:11
> @its-VinayKumar, it has been more than a month since the issue was assigned to you. Are you still working on this issue?
> 
> // @Cioppolo14

I would like to work on this issue : ).

**Comment by palisadoes** [comment] 2024-03-02 16:19
Assigning to @akhilender-bongirwar who raised the concern.

1. The User profile screen has changed significantly in the figma design. 
2. Please reference it and any related open issues prior to starting

**Closed** 2024-03-24 06:52 UTC
Labels: feature request, no-issue-activity, figma
