### ISSUE TITLE
unified login and registration form component for admin portal and user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1424] opened 2024-01-13 23:21 UTC
**Is your feature request related to a problem? Please describe.**
We aim to create a unified login and registration form component, tailoring its behavior through props for both user and admin login screens.

**Describe the solution you'd like**
make a single component and pass the required props 

**Additional context**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment] 2024-01-14 03:40
Hey I would like to solve this issue!

**Comment by AVtheking** [comment] 2024-01-14 05:50
I would like to work on this issue

**Comment by nakul30** [comment] 2024-01-14 13:41
> **Is your feature request related to a problem? Please describe.** We aim to create a unified login and registration form component, tailoring its behavior through props for both user and admin login screens.
> 
> **Describe the solution you'd like** make a single component and pass the required props
> 
> **Additional context** NA
> 
> **Potential internship candidates** Please read this if you are planning to apply for a Palisadoes Foundation internship [PalisadoesFoundation/talawa#359](https://github.com/PalisadoesFoundation/talawa/issues/359)

But these both are already present in the single component

**Comment by adi790uu** [comment] 2024-01-23 15:37
Hey @aashimawadhwa @Cioppolo14  what should be done about the tests for Login pages, should i keep the AdminLogin and UserLogin tests as seperate files or make it such that it is a single file?

**Comment by aashimawadhwa** [comment] 2024-01-24 07:37
So go ahead like this,
- make two seprate components user and admin and test file for each of them
 - finally make a login component and teat file for it and render admin and user login here.
 I hope this clears all your doubts.

**Comment by rishabhbizzle** [comment] 2024-01-24 07:46
This issue is a duplicate of #1377 @aashimawadhwa which I've already fixed (check the video I had attached in the issue replies) and will be raising PR for it very shortly.

**Comment by aashimawadhwa** [comment] 2024-01-24 07:49
It's been 3 weeks for the issue what's the actual status? @rishabhbizzle

**Comment by aashimawadhwa** [comment] 2024-01-24 07:49
@Cioppolo14 we can close this issue as it is a duplicate one.

**Closed** 2024-01-24 07:53 UTC
Labels: feature request
